codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 30%
        threshold: 1%
        flags:
          - macos-app
    patch:
      default:
        target: auto
        threshold: 5%
        flags:
          - macos-app

flags:
  macos-app:
    carryforward: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
